# Generated by Django 4.2.1 on 2023-05-17 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Country', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Street', models.CharField(max_length=30)),
                ('HouseNumber', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('DateOfAppearance', models.DateTimeField(verbose_name='Дата выхода на рынок')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], verbose_name='Роль')),
                ('name', models.CharField(max_length=30)),
                ('debt', models.DecimalField(decimal_places=2, max_digits=19)),
                ('TimeCreate', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='links.contact', verbose_name='Контакты')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='links.product', verbose_name='Продукты')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='links.link', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Звено',
                'verbose_name_plural': 'Звенья',
            },
        ),
    ]
