# Generated by Django 4.2.1 on 2023-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_level_alter_link_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='City',
            field=models.CharField(max_length=30, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Country',
            field=models.CharField(max_length=30, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='HouseNumber',
            field=models.PositiveSmallIntegerField(verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Street',
            field=models.CharField(max_length=30, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='link',
            name='debt',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Задолженность перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=30, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
    ]
