# Generated by Django 4.2.1 on 2023-05-21 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_contact_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='products',
        ),
        migrations.AlterField(
            model_name='link',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_level', to='links.link', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='link',
            name='products',
            field=models.ManyToManyField(to='links.product', verbose_name='Продукты'),
        ),
    ]
